// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddEntry(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddEntry'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteEntries(arg1, arg2) {
  return window['go']['main']['App']['DeleteEntries'](arg1, arg2);
}

export function ExportVault(arg1) {
  return window['go']['main']['App']['ExportVault'](arg1);
}

export function GeneratePassword(arg1) {
  return window['go']['main']['App']['GeneratePassword'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetEntryHistory(arg1) {
  return window['go']['main']['App']['GetEntryHistory'](arg1);
}

export function GetTOTPCode(arg1) {
  return window['go']['main']['App']['GetTOTPCode'](arg1);
}

export function ImportVault(arg1) {
  return window['go']['main']['App']['ImportVault'](arg1);
}

export function Initialize(arg1) {
  return window['go']['main']['App']['Initialize'](arg1);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListEntries(arg1) {
  return window['go']['main']['App']['ListEntries'](arg1);
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function SearchEntries(arg1) {
  return window['go']['main']['App']['SearchEntries'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateEntry(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateEntry'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
