// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCategory(arg1:string):Promise<number>;

export function AddEntry(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function GeneratePassword(arg1:number):Promise<string>;

export function GetCategories():Promise<Array<main.Category>>;

export function Initialize(arg1:string):Promise<void>;

export function IsInitialized():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function ListEntries(arg1:number):Promise<Array<main.Entry>>;

export function Lock():Promise<void>;

export function RenameCategory(arg1:number,arg2:string):Promise<void>;

export function SearchEntries(arg1:string):Promise<Array<main.Entry>>;

export function Unlock(arg1:string):Promise<void>;

export function UpdateEntry(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;
